// Put this file in the same root/folder as index.html
// Expand by adding more objects with the same keys:
// base, method ("erest" or "moremost"), comparative, superlative

window.COMPARATIVE_BANK = [
  // -er / -est
  { base: "small", method: "erest", comparative: "smaller", superlative: "the smallest" },
  { base: "fast", method: "erest", comparative: "faster", superlative: "the fastest" },
  { base: "tall", method: "erest", comparative: "taller", superlative: "the tallest" },
  { base: "short", method: "erest", comparative: "shorter", superlative: "the shortest" },
  { base: "long", method: "erest", comparative: "longer", superlative: "the longest" },
  { base: "young", method: "erest", comparative: "younger", superlative: "the youngest" },
  { base: "old", method: "erest", comparative: "older", superlative: "the oldest" },
  { base: "cold", method: "erest", comparative: "colder", superlative: "the coldest" },
  { base: "warm", method: "erest", comparative: "warmer", superlative: "the warmest" },
  { base: "high", method: "erest", comparative: "higher", superlative: "the highest" },
  { base: "low", method: "erest", comparative: "lower", superlative: "the lowest" },
  { base: "slow", method: "erest", comparative: "slower", superlative: "the slowest" },
  { base: "bright", method: "erest", comparative: "brighter", superlative: "the brightest" },
  { base: "dark", method: "erest", comparative: "darker", superlative: "the darkest" },
  { base: "clean", method: "erest", comparative: "cleaner", superlative: "the cleanest" },
  { base: "cheap", method: "erest", comparative: "cheaper", superlative: "the cheapest" },
  { base: "rich", method: "erest", comparative: "richer", superlative: "the richest" },
  { base: "poor", method: "erest", comparative: "poorer", superlative: "the poorest" },
  { base: "great", method: "erest", comparative: "greater", superlative: "the greatest" },
  { base: "strong", method: "erest", comparative: "stronger", superlative: "the strongest" },
  { base: "weak", method: "erest", comparative: "weaker", superlative: "the weakest" },
  { base: "happy", method: "erest", comparative: "happier", superlative: "the happiest" },
  { base: "busy", method: "erest", comparative: "busier", superlative: "the busiest" },
  { base: "easy", method: "erest", comparative: "easier", superlative: "the easiest" },
  { base: "heavy", method: "erest", comparative: "heavier", superlative: "the heaviest" },

  // more / most
  { base: "careful", method: "moremost", comparative: "more careful", superlative: "the most careful" },
  { base: "famous", method: "moremost", comparative: "more famous", superlative: "the most famous" },
  { base: "modern", method: "moremost", comparative: "more modern", superlative: "the most modern" },
  { base: "comfortable", method: "moremost", comparative: "more comfortable", superlative: "the most comfortable" },
  { base: "interesting", method: "moremost", comparative: "more interesting", superlative: "the most interesting" },
  { base: "expensive", method: "moremost", comparative: "more expensive", superlative: "the most expensive" },
  { base: "beautiful", method: "moremost", comparative: "more beautiful", superlative: "the most beautiful" },
  { base: "dangerous", method: "moremost", comparative: "more dangerous", superlative: "the most dangerous" },
  { base: "difficult", method: "moremost", comparative: "more difficult", superlative: "the most difficult" },
  { base: "popular", method: "moremost", comparative: "more popular", superlative: "the most popular" },
  { base: "important", method: "moremost", comparative: "more important", superlative: "the most important" },
  { base: "delicious", method: "moremost", comparative: "more delicious", superlative: "the most delicious" },
  { base: "convenient", method: "moremost", comparative: "more convenient", superlative: "the most convenient" },
  { base: "effective", method: "moremost", comparative: "more effective", superlative: "the most effective" },
  { base: "creative", method: "moremost", comparative: "more creative", superlative: "the most creative" },
  { base: "crowded", method: "moremost", comparative: "more crowded", superlative: "the most crowded" },
  { base: "polite", method: "moremost", comparative: "more polite", superlative: "the most polite" },
  { base: "honest", method: "moremost", comparative: "more honest", superlative: "the most honest" },
  { base: "useful", method: "moremost", comparative: "more useful", superlative: "the most useful" },
  { base: "helpful", method: "moremost", comparative: "more helpful", superlative: "the most helpful" },
  { base: "powerful", method: "moremost", comparative: "more powerful", superlative: "the most powerful" },
  { base: "successful", method: "moremost", comparative: "more successful", superlative: "the most successful" },
  { base: "amazing", method: "moremost", comparative: "more amazing", superlative: "the most amazing" },
  { base: "exciting", method: "moremost", comparative: "more exciting", superlative: "the most exciting" },
  { base: "boring", method: "moremost", comparative: "more boring", superlative: "the most boring" }
];
